### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by barelyelectric** [fletchto99/nicotine-plus-docker#1]
![dark_mode](https://github.com/fletchto99/nicotine-plus-docker/assets/71984727/b0711c9a-0094-4974-af0f-c7cb64292f44)

I can't get dark mode to enable for some reason, restarting the container has no effect. Is there a system theme variable we could have for the container?

**Comment by slook** [comment]
To do that you would probably have to bundle some dark GTK theme in the package.

**Comment by syphant** [comment]
+1 if implemented I would shower you in love and affection, thx

**Comment by fletchto99** [comment]
I don't plan to implement this in the near future but am accepting pull requests if someone else would like to take a shot at it.

**Comment by barelyelectric** [comment]
dark mode works in latest version

**Comment by fletchto99** [comment]
Awesome looks like the automatic dependency updates caught this 🎉
