### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by minicoz** [fletchto99/nicotine-plus-docker#3]
How can we update the nicotine+ version automatically?

**Comment by fletchto99** [comment]
A new package is built daily. You can pull from GHCR or Docker Hub using the latest tag and use something like https://containrrr.dev/watchtower/ to update your containers on a schedule.

**Comment by fletchto99** [comment]
During the nightly build process it's installed via the dockerfile: https://github.com/fletchto99/nicotine-plus-docker/blob/main/Dockerfile#L46

So when docker build runs it'll grab the latest version
