### ISSUE TITLE
Include a Listening Port ENV Var

### ISSUE THREAD

**Issue by minicoz** [fletchto99/nicotine-plus-docker#4]
Im using the docker compose version of this.

It would be nice to include the LISTENING_PORT Env variable so that I can set it from the compose file.
It seems like nicotine+ does have a cli arg here
https://github.com/nicotine-plus/nicotine-plus/blob/master/pynicotine/__init__.py#L74

that would start the app with that port number. Could we pass in the ENV in the Dockerfile and then send in the listening port arg in the `autostart` file? 

I use this container with gluetun VPN and sometimes glueutn will change the port number for my port forward.

**Comment by fletchto99** [comment]
Does the `CUSTOM_PORT` variable not work in this case? It changes the HTTP port that the VNC viewer listens on.

**Comment by fletchto99** [comment]
Ahh I see. Makes sense, thanks! Once you have a chance to test out the PR I'm happy to accept the change.

**Comment by fletchto99** [comment]
Thanks for your contribution!
