### ISSUE TITLE
OpenBox/AutoStart Config: Syntax Error

### ISSUE THREAD

**Issue by quixote23** [fletchto99/nicotine-plus-docker#8]
Today (or maybe starting a few days ago, I haven't accessed N+ in about a week) I tried to open the interface and just got a black screen.

In Docker logs I am seeing: 

2024-11-06 15:37:47 /config/.config/openbox/autostart: 1: Syntax error: "(" unexpected

**Comment by minicoz** [comment]
try pulling the latest image again. It gets rebuilt every night from the nicotine plus official release so if something broke on their side, we would see it on this docker release. Mine is working fine.

**Comment by fletchto99** [comment]
Sounds like this was fixed. Please re-open if it is not and I'll try to get around to it at some point
